<a href="https://colab.research.google.com/github/Sumetjutha/MyProject/blob/main/22_Cleasing_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=np.random.randn(5, 3)
print(df)

[[ 2.1345653   0.28472337 -1.08294174]
 [-2.58223014 -1.4468391   0.24568364]
 [-0.23461917 -0.1302645  -0.63575551]
 [-0.54102467  0.40986625  1.4440222 ]
 [-1.07949129 -0.70382138 -2.02958724]]


In [ ]:
df = pd.DataFrame(df, index=['a', 'c', 'e', 'f','h'],columns=['one', 'two', 'three'])

In [ ]:
print(df)

        one       two     three
a  2.134565  0.284723 -1.082942
c -2.582230 -1.446839  0.245684
e -0.234619 -0.130265 -0.635756
f -0.541025  0.409866  1.444022
h -1.079491 -0.703821 -2.029587


In [ ]:
df = df.reindex(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'])

In [ ]:
print(df)

        one       two     three
a  2.134565  0.284723 -1.082942
b       NaN       NaN       NaN
c -2.582230 -1.446839  0.245684
d       NaN       NaN       NaN
e -0.234619 -0.130265 -0.635756
f -0.541025  0.409866  1.444022
g       NaN       NaN       NaN
h -1.079491 -0.703821 -2.029587


In [ ]:
## Check Missing
print(df['one'].isnull())

a    False
b     True
c    False
d     True
e    False
f    False
g     True
h    False
Name: one, dtype: bool


In [ ]:
df = df.reindex(['a', 'b', 'c'])

In [ ]:
df.fillna(method='pad')

In [ ]:
## Fill missing=na with 0
df.fillna(0)

one       two     three
a  2.134565  0.284723 -1.082942
b  0.000000  0.000000  0.000000
c -2.582230 -1.446839  0.245684
d  0.000000  0.000000  0.000000
e -0.234619 -0.130265 -0.635756
f -0.541025  0.409866  1.444022
g  0.000000  0.000000  0.000000
h -1.079491 -0.703821 -2.029587

In [ ]:
## fill na with forward filling
df.fillna(method='ffill')

one       two     three
a  2.134565  0.284723 -1.082942
b  2.134565  0.284723 -1.082942
c -2.582230 -1.446839  0.245684
d -2.582230 -1.446839  0.245684
e -0.234619 -0.130265 -0.635756
f -0.541025  0.409866  1.444022
g -0.541025  0.409866  1.444022
h -1.079491 -0.703821 -2.029587